import { mockMusicianProfiles } from '@/api/profiles/services/mock';

import type { JamSession } from './types';

export const mockJamSessions: JamSession[] = [
  {
    id: 'jam1',
    title: 'Wednesday Jazz Jam',
    image: 'https://i.pinimg.com/736x/7e/70/a0/7e70a055856e7799e54213cba928cba3.jpg',
    description:
      "Relaxed jazz session in downtown. All skill levels welcome! We'll have a piano and drum kit available.",
    host: mockMusicianProfiles[1],
    date: '2025-01-19',
    time: '14:00',
    location: 'Blue Note Cafe',
    address: '1234 Jazz Street, Seattle, WA 98101',
    maxParticipants: 6,
    currentParticipants: 3,
    genres: ['Jazz', 'Blues'],
    skillLevel: 'All Levels',
    type: 'open',
    participants: [mockMusicianProfiles[2], mockMusicianProfiles[0]],
    setlist: [
      {
        id: 'song1',
        title: 'Autumn Leaves',
        artist: 'Joseph Kosma',
        genre: 'Jazz',
        difficulty: 'Medium',
        suggestedBy: mockMusicianProfiles[1].name || 'Unknown',
      },
      {
        id: 'song2',
        title: 'Blue Monk',
        artist: 'Thelonious Monk',
        genre: 'Jazz',
        difficulty: 'Easy',
        suggestedBy: mockMusicianProfiles[2].name || 'Unknown',
      },
    ],
    neededInstruments: ['Bass', 'Trumpet'],
    equipment: ['Piano', 'Drum Kit', 'PA System'],
    price: 15,
    discussion: [
      {
        id: 'thread1',
        author: { ...mockMusicianProfiles[1] },
        content: 'Looking forward to jamming with everyone! Any song requests?',
        timestamp: '2025-01-10T10:00:00Z',
        replies: [
          {
            id: 'reply1',
            author: { ...mockMusicianProfiles[2] },
            content: "Can we play 'Blue Monk'?",
            timestamp: '2025-01-10T11:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'jam2',
    title: 'Indie Rock Night',
    image:
      'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80',
    description:
      'Bring your guitar and join us for a night of indie rock covers and originals. Open to all guitarists and singers!',
    host: mockMusicianProfiles[2],
    date: '2025-01-22',
    time: '19:00',
    location: 'Echo Studio',
    address: '5678 Indie Ave, Seattle, WA 98102',
    maxParticipants: 8,
    currentParticipants: 5,
    genres: ['Indie Rock', 'Alternative'],
    skillLevel: 'Intermediate',
    type: 'open',
    participants: [
      mockMusicianProfiles[3],
      mockMusicianProfiles[0],
      mockMusicianProfiles[1],
      mockMusicianProfiles[4],
    ],
    setlist: [
      {
        id: 'song3',
        title: 'Take Me Out',
        artist: 'Franz Ferdinand',
        genre: 'Indie Rock',
        difficulty: 'Medium',
        suggestedBy: mockMusicianProfiles[2].name || 'Unknown',
      },
      {
        id: 'song4',
        title: 'Mr. Brightside',
        artist: 'The Killers',
        genre: 'Alternative',
        difficulty: 'Hard',
        suggestedBy: mockMusicianProfiles[3].name || 'Unknown',
      },
    ],
    neededInstruments: ['Guitar', 'Vocals'],
    equipment: ['Guitar Amps', 'Microphones', 'PA System'],
    price: 10,
    discussion: [
      {
        id: 'thread2',
        author: { ...mockMusicianProfiles[2] },
        content: "Who's bringing pedals?",
        timestamp: '2025-01-15T09:00:00Z',
        replies: [
          {
            id: 'reply2',
            author: { ...mockMusicianProfiles[3] },
            content: "I'll bring my pedalboard!",
            timestamp: '2025-01-15T09:30:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'jam3',
    title: 'Sunday Acoustic Circle',
    image:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    description:
      'Unplugged acoustic jam for singer-songwriters. Share your originals or play along with others.',
    host: mockMusicianProfiles[0],
    date: '2025-01-21',
    time: '16:00',
    location: 'Green Lake Park',
    address: '9101 Park Lane, Seattle, WA 98103',
    maxParticipants: 12,
    currentParticipants: 7,
    genres: ['Folk', 'Acoustic', 'Singer-Songwriter'],
    skillLevel: 'All Levels',
    type: 'open',
    participants: [
      mockMusicianProfiles[1],
      mockMusicianProfiles[2],
      mockMusicianProfiles[3],
      mockMusicianProfiles[4],
      mockMusicianProfiles[5],
      mockMusicianProfiles[6],
    ],
    setlist: [
      {
        id: 'song5',
        title: 'Fast Car',
        artist: 'Tracy Chapman',
        genre: 'Folk',
        difficulty: 'Medium',
        suggestedBy: mockMusicianProfiles[0].name || 'Unknown',
      },
      {
        id: 'song6',
        title: 'Wonderwall',
        artist: 'Oasis',
        genre: 'Acoustic',
        difficulty: 'Easy',
        suggestedBy: mockMusicianProfiles[1].name || 'Unknown',
      },
    ],
    neededInstruments: ['Acoustic Guitar', 'Cajon'],
    equipment: ['None'],
    price: 0,
    discussion: [
      {
        id: 'thread3',
        author: { ...mockMusicianProfiles[0], songs: undefined },
        content: "Let's keep it unplugged and mellow!",
        timestamp: '2025-01-18T14:00:00Z',
        replies: [],
      },
    ],
  },
  {
    id: 'jam4',
    title: 'Funk Groove Session',
    image: 'https://i.pinimg.com/1200x/70/5a/8e/705a8e344cdaf65ed88ec6ea802e8755.jpg',
    description:
      'Get your groove on with our monthly funk jam. Bassists and drummers especially welcome!',
    host: mockMusicianProfiles[3],
    date: '2025-01-25',
    time: '20:00',
    location: 'Groove Basement',
    address: '2222 Funky St, Seattle, WA 98104',
    maxParticipants: 10,
    currentParticipants: 6,
    genres: ['Funk', 'Soul'],
    skillLevel: 'Advanced',
    type: 'invite',
    participants: [
      mockMusicianProfiles[0],
      mockMusicianProfiles[1],
      mockMusicianProfiles[2],
      mockMusicianProfiles[4],
      mockMusicianProfiles[5],
    ],
    setlist: [
      {
        id: 'song7',
        title: 'Superstition',
        artist: 'Stevie Wonder',
        genre: 'Funk',
        difficulty: 'Hard',
        suggestedBy: mockMusicianProfiles[3].name || 'Unknown',
      },
      {
        id: 'song8',
        title: 'Pick Up the Pieces',
        artist: 'Average White Band',
        genre: 'Funk',
        difficulty: 'Medium',
        suggestedBy: mockMusicianProfiles[0].name || 'Unknown',
      },
    ],
    neededInstruments: ['Bass', 'Drums', 'Keys'],
    equipment: ['Bass Amp', 'Drum Kit', 'Keyboard'],
    price: 20,
    discussion: [
      {
        id: 'thread4',
        author: { ...mockMusicianProfiles[3] },
        content: "Who's ready to groove?",
        timestamp: '2025-01-20T17:00:00Z',
        replies: [
          {
            id: 'reply3',
            author: { ...mockMusicianProfiles[0] },
            content: "Can't wait! I'll bring my clav.",
            timestamp: '2025-01-20T17:30:00Z',
          },
        ],
      },
    ],
  },
];
